# Generated by Django 5.2.4 on 2025-08-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASLSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Sign name (e.g., 'A', 'Hello', '1')", max_length=100)),
                ('image', models.ImageField(help_text='Upload ASL sign image', upload_to='asl_signs/')),
                ('category', models.CharField(choices=[('alphabet', 'Alphabet'), ('numbers', 'Numbers'), ('common', 'Common Words'), ('phrases', 'Phrases')], max_length=20)),
                ('description', models.TextField(help_text='Description of the sign')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'label'],
            },
        ),
    ]
