# Generated by Django 5.2.4 on 2025-08-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aslsign',
            name='description',
        ),
        migrations.AlterField(
            model_name='aslsign',
            name='category',
            field=models.CharField(choices=[('alphabet', 'Alphabet'), ('numbers', 'Numbers'), ('common', 'Common Words')], max_length=20),
        ),
    ]
